-- Create an initial super admin user
-- First, create a user in Supabase Auth (this needs to be done through Supabase dashboard or API)

-- Then, after creating the user in Auth, insert into the admins table with the user's UUID
-- Replace 'your-email@example.com' and 'Your Full Name' with actual values
-- The UUID should match the one generated by Supabase when you create the user

-- Example (you need to replace 'user-uuid-here' with the actual UUID from Supabase Auth):
-- INSERT INTO admins (id, email, full_name, role) 
-- VALUES ('user-uuid-here', 'admin@example.com', 'Admin User', 'super_admin');

-- Note: To get the actual UUID, you can either:
-- 1. Check the auth.users table in Supabase Studio
-- 2. Create the user through the Supabase dashboard and note the UUID
-- 3. Use the Supabase Auth API to create a user programmatically